- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- app/views/_user_util_links.html.erb
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20160114233535_add_omni_auth_to_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/features/sign_in_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/support/capybara.rb
- spec/support/factory_girl.rb
- spec/support/features/session_helpers.rb
- spec/support/reset_auth.rb
> Add CAS authentication.

- Capfile
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/user.rb
- config/blacklight.yml
- config/database.yml
- config/deploy.rb
- config/deploy/staging.rb
- config/environments/staging.rb
- config/secrets.yml
- db/migrate/20160111171277_create_spotlight_exhibit_filters.spotlight.rb
> Enable Pomegranate Deploys

- app/assets/stylesheets/viewer.scss
- app/controllers/catalog_controller.rb
- app/models/collection_manifest.rb
- app/models/iiif_resource.rb
- app/views/catalog/_universal_viewer_default.html.erb
- config/config.yml
- spec/cassettes/all_collections.yml
This indexes the manifest URL and uses a hosted Universal Viewer.
> Use Universal Viewer.

- app/models/iiif_resource.rb
- app/models/solr_document.rb
- app/views/catalog/_show_default.html.erb
- spec/models/iiif_resource_spec.rb
- spec/spec_helper.rb
- spec/views/catalog/_show_default.html.erb_spec.rb
> Display More Metadata

- app/models/solr_document.rb
> Hide extra metadata.

- Gemfile
- Gemfile.lock
Needed for Sneakers to work with the new Redis namespace.
> Add redis-namespace gem.

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/catalog_controller.rb
- app/presenters/rtl_presenter.rb
- config/initializers/spotlight_config.rb
- spec/presenters/rtl_presenter_spec.rb
> Render RTL text appropriately in show view.

- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/models/search_builder.rb
- app/models/search_builder/join_children_query.rb
- spec/cassettes/mvw.yml
- spec/controllers/catalog_controller_spec.rb
- spec/models/iiif_resource_spec.rb
> Find MVW from Children

- Gemfile
- Gemfile.lock
- app/queries/external_collections_query.rb
- spec/cassettes/no_collections.yml
- spec/controllers/exhibits_controller_spec.rb
- spec/queries/external_collections_query_spec.rb
> Don't crash if there are no exhibits.

- app/models/user.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
> Not everyone should be a site admin.

- app/services/plum_event_processor/update_processor.rb
- app/views/spotlight/catalog/_document_visibility_control.html.erb
- spec/cassettes/plum_events_no_permission.yml
- spec/services/plum_event_processor_spec.rb
> Suppressing from Plum makes item private in Pomegranate

- Gemfile
- Gemfile.lock
> Index full image URL for use in blocks.

- Gemfile
- Gemfile.lock
- app/queries/external_collections_query.rb
- app/views/spotlight/exhibits/_new_exhibit_form.html.erb
- spec/queries/external_collections_query_spec.rb
- spec/support/database_cleaner.rb
- spec/views/spotlight/exhibits/_new_exhibit_form.html.erb_spec.rb
> Only display uncreated exhibits.

- app/services/plum_event_processor/delete_processor.rb
- spec/services/plum_event_processor_spec.rb
> Fix syncing deletes

- app/workers/plum_event_handler.rb
- config/initializers/sneakers.rb
Configures sneakers to use the maxretry handler. Closes #112
> Configure sneakers to use maxretry handler

- Gemfile
- Gemfile.lock
Adds riiif to gemfile. Needed, for now, to keep sidekiq workers running.
> Add riiif to gemfile

- app/values/manifest_metadata.rb
- spec/cassettes/all_collections.yml
- spec/cassettes/mvw.yml
- spec/cassettes/plum_events.yml
- spec/cassettes/plum_events_no_permission.yml
- spec/cassettes/see_also_connection_failed.yml
- spec/models/iiif_resource_spec.rb
Index from json-ld instead of metadata pool. Closes #121
> Index from json-ld

- config/config.yml
- config/database.yml
- config/deploy.rb
- config/deploy/production.rb
> Add configuration for production deploys.

- config/database.yml
Fixes production synchronization.
> Increase pool size for sneakers workers.

- app/assets/stylesheets/application.scss
> Allow for long scrollable descriptions on cards

- app/assets/stylesheets/application.scss
> Fix metadata spacing.

- .rubocop.yml
- app/controllers/catalog_controller.rb
> Remove bookmarks and saved searches.

- app/assets/stylesheets/application.scss
> Fix facet carat alignment.

- app/controllers/catalog_controller.rb
> Embed universal viewer instead of OSD.

- app/assets/stylesheets/application.scss
> Adjust search form box.

- app/helpers/spotlight_helper.rb
- app/presenters/rtl_show_presenter.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Fix RTL titles.

- app/decorators/applies_title_from_slug.rb
- app/models/collection_manifest.rb
- app/views/spotlight/exhibits/_new_exhibit_form.html.erb
> Fix collection title being an array.

- app/views/spotlight/metadata_configurations/edit.html.erb
- spec/views/spotlight/metadata_configurations/edit.html.erb_spec.rb
These already have all the necessary functionality, it just clutters the
UI.
> Don't allow readonly custom fields to be edited.

- app/controllers/catalog_controller.rb
- config/initializers/spotlight_config.rb
> Hide duplicate fields in metadata pane.

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/layouts/spotlight/spotlight.html.erb
- app/views/shared/_announcements.html.erb
> Add beta banner.

- app/helpers/application_helper.rb
> Fix site header in cross-search

- config/locales/en.yml
> Change label to metadata configuration.

- app/assets/stylesheets/application.scss
> Fix facet positioning.

- app/controllers/catalog_controller.rb
> Remove bookmark checkbox.

- app/assets/stylesheets/application.scss
> Increase header size of search result titles.

- app/assets/stylesheets/application.scss
> Princeton orange title.

- app/controllers/exhibits_controller.rb
- app/models/iiif_resource.rb
- config/routes.rb
- spec/controllers/exhibits_controller_spec.rb
> Clean up solr when destroying an exhibit.

- Gemfile
- Gemfile.lock
> Make imported facets not display by default

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> Add requested fields to cross-collection search

- app/models/collection_manifest.rb
- spec/cassettes/all_collections.yml
> Don't depend on embedded manifests.

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/catalog_controller.rb
- app/jobs/spotlight/reindex_job.rb
- app/models/exhibit_proxy.rb
- app/services/plum_event_processor/update_processor.rb
- app/views/shared/_masthead.html.erb
- config/initializers/riiif.rb
- config/routes.rb
- db/migrate/20170203221026_add_iiif_urls_to_featured_image.spotlight.rb
- db/migrate/20170203221027_add_iiif_url_to_contact.spotlight.rb
- db/migrate/20170203221028_add_upload_id_to_resources.spotlight.rb
- db/migrate/20170203221029_add_document_index_to_solr_document_sidecar.spotlight.rb
- db/migrate/20170203221030_create_spotlight_reindexing_log_entries.spotlight.rb
- db/schema.rb
- spec/cassettes/no_collections.yml
- spec/models/iiif_resource_spec.rb
- spec/services/plum_event_processor_spec.rb
We'll have to reindex everything in production to get this to work, but it works really well.
> Update Spotlight for IIIF-Crop

- config/routes.rb
- spec/routing/exhibits_routing_spec.rb
- spec/views/spotlight/exhibits/_new_exhibit_form.html.erb_spec.rb
> Have everything come off the root.

- app/views/_user_util_links.html.erb
> Add home link

- app/assets/stylesheets/application.scss
- app/views/shared/_masthead.html.erb
> Fix browse category CSS

- Gemfile
- Gemfile.lock
> Use spotlight that has fixed facet limits

- app/assets/stylesheets/application.scss
> Don't push metadata below thumbnail

- app/values/manifest_metadata.rb
- spec/cassettes/all_collections.yml
- spec/models/iiif_resource_spec.rb
> Index Memberof as Collections

- config/sidekiq.yml
20 was way too many for the system to handle.
> Lower sidekiq worker count.

- app/controllers/catalog_controller.rb
- app/decorators/applies_title_from_slug.rb
- app/models/exhibit_proxy.rb
- app/models/solr_document.rb
- app/repositories/friendly_id_repository.rb
- app/services/iiif_manifest.rb
- config/routes.rb
- config/sidekiq.yml
- spec/jobs/spotlight/reindex_job_spec.rb
Closes #249 
Closes #248 
Closes #247
> Fix errors

- app/controllers/catalog_controller.rb
- app/models/search_across_search_builder.rb
- spec/controllers/catalog_controller_spec.rb
> Hide unpublished/private items from cross-search

- .rubocop.yml
- app/models/solr_document.rb
- app/presenters/rtl_index_presenter.rb
- app/presenters/rtl_show_presenter.rb
- spec/presenters/rtl_index_presenter_spec.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Display special encoding from solr.

- app/assets/stylesheets/application.scss
> Don't display scrollbar for front flipcards

- public/robots.txt
> Slow down robots and disallow indexing search results pages

- app/controllers/catalog_controller.rb
Fixes search across. Closes #298
> Make sure it's only displaying unique fields.

- Gemfile
- Gemfile.lock
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/exhibits_controller_spec.rb
- spec/factories/exhibits.rb
- spec/factories/users.rb
- spec/features/exhibit_home_page_spec.rb
- spec/features/sign_in_spec.rb
- spec/models/user_spec.rb
- spec/queries/external_collections_query_spec.rb
- spec/services/plum_event_processor_spec.rb
- spec/support/factory_girl.rb
- spec/support/features/session_helpers.rb
- spec/views/spotlight/exhibits/_new_exhibit_form.html.erb_spec.rb
- spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb
- spec/views/spotlight/metadata_configurations/edit.html.erb_spec.rb
> Upgrade from FactoryGirl to FactoryBot.

- app/models/search_builder.rb
- app/models/search_builder/join_children_query.rb
- spec/controllers/catalog_controller_spec.rb
- spec/features/catalog_spec.rb
> Ensuring that quotes are properly escaped within the dismax parameters for joining on child resource Documents

- config/deploy.rb
> Add ugly hack to keep staging deploy working until new box is ready

- .rubocop.yml
- app/controllers/catalog_controller.rb
- app/services/iiif_manifest.rb
- spec/controllers/catalog_controller_spec.rb
- spec/fixtures/iiif_responses.rb
- spec/models/iiif_resource_spec.rb
- spec/repositories/friendly_id_repository_spec.rb
- spec/services/iiif_manifest_spec.rb
- spec/support/stub_iiif_response.rb
> Add new sort fields for title, date, and author

- app/workers/plum_event_handler.rb
- spec/workers/plum_event_handler_spec.rb
Sneakers retries rejects, when really we just don't want to do anything.
> Don't reject unknown types.

- Gemfile
- Gemfile.lock
- app/workers/plum_event_handler.rb
- config/database.yml
Occasionally the sneakers workers are unable to obtain a connection from
the database for some reason. Attempting to validate the connection at
the start of the work as well as updating dependencies will hopefully
either fix the issue or give us some idea of what's going on better.
> Update pg/sneakers/reaping frequency

- app/models/user.rb
- config/initializers/devise.rb
- spec/models/user_spec.rb
> Allow non-existing users to be added as admins.

- app/presenters/rtl_show_presenter.rb
- app/services/iiif_manifest.rb
- spec/cassettes/mvw.yml
- spec/models/iiif_resource_spec.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Split HTML title with commas, not <br>

- .rubocop.yml
- app/controllers/catalog_controller.rb
- app/services/iiif_manifest.rb
- spec/controllers/catalog_controller_spec.rb
- spec/fixtures/iiif_responses.rb
- spec/models/iiif_resource_spec.rb
- spec/repositories/friendly_id_repository_spec.rb
- spec/services/iiif_manifest_spec.rb
- spec/support/stub_iiif_response.rb
This reverts commit ad9434bc65f4271bdd69c83a07c6ee566c869722.
Closes #307
> Re-add Sort Orders

- app/views/shared/_masthead.html.erb
- spec/features/exhibit_home_page_spec.rb
> Enable RTL subtitles on exhibits.

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> Ensures that Collections are faceted and indexed between exhibits

- app/queries/external_collections_query.rb
- spec/queries/external_collections_query_spec.rb
> Sorting collection list by title

- app/views/shared/_announcements.html.erb
> Remove beta banner.

- README.md
- app/jobs/spotlight/reindex_job.rb
- spec/fixtures/iiif_responses.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/models/exhibit_proxy_spec.rb
- spec/repositories/friendly_id_repository_spec.rb
- spec/services/iiif_manifest_spec.rb
- spec/services/iiif_service_spec.rb
Resolves #371 by extending the test coverage for:
- IIIFService
- ReindexJob
- ExhibitProxy
- FriendlyIdRepository
> Extend test coverage to 100%

- app/views/spotlight/exhibits/index.html.erb
> Remove sidebar column from front page

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
> Switch capybara from poltergeist to headless-chrome

- app/assets/stylesheets/application.scss
> Fix text wrapping.

- app/views/catalog/_previous_next_doc.html.erb
- app/views/catalog/_show_tools.html.erb
* Reverts #419 
* Correctly suppresses broken buttons
> Correctly suppressing broken buttons

- app/models/iiif_resource.rb
- spec/models/iiif_resource_spec.rb
- spec/spec_helper.rb
- spec/support/vcr.rb
Resolves #336 by logging an error with a URL to the invalid Manifest
> Implements IIIFResource#validate_iiif_manifest_collections! for validating IIIF Manifest Collection metadata

- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- Updates rack to close security vulnerability.
- Cleans up the Gemfile
Closes #443
>  Update rack gem

- app/models/solr_document.rb
- spec/models/solr_document_spec.rb
> Remove Dublin Core export formats

- app/views/catalog/index.html.erb
> Override catalog index view to default to a blank search

- app/assets/stylesheets/application.scss
> Fixes modal shift on the top in firefox

- .rubocop.yml
- app/processors/custom_field_rendering.rb
> Make thumbnails HTML-safe

- app/models/ability.rb
- spec/models/ability_spec.rb
Fix copied from https://github.com/sul-dlss/exhibits/pull/440
fixes #271
> Add ability for creating Spotlight::FeaturedImage

- config/environments/production.rb
> Update mailer host in prod

- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- app/views/catalog/_default_search_form.html.erb
- config/routes.rb
- spec/features/error_page_spec.rb
- spec/requests/catalog_spec.rb
Fixes https://github.com/pulibrary/pomegranate/issues/481
> Trap errors trying to render search bar

- app/jobs/iiif_ingest_job.rb
- app/models/exhibit_proxy.rb
- app/models/iiif_resource.rb
- spec/jobs/iiif_ingest_job_spec.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/models/iiif_resource_spec.rb
> Fix reindex progress bar

- app/values/manifest_metadata.rb
- spec/values/manifest_metadata_spec.rb
> Index Ephemera Vocabulary pref_labels

- app/helpers/application_helper.rb
- app/presenters/rtl_index_presenter.rb
- app/presenters/rtl_show_presenter.rb
- app/services/iiif_manifest.rb
- app/values/manifest_metadata.rb
- app/views/spotlight/catalog/_edit_default.html.erb
- config/initializers/monkeypatches/spotlight_breadcrumb_patch.rb
- spec/presenters/rtl_index_presenter_spec.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Allow for titles to be changed.

- app/assets/stylesheets/application.scss
> Fix browse category title color.

- Gemfile
- Gemfile.lock
- app/services/figgy_graphql.rb
- app/services/iiif_manifest.rb
- spec/controllers/catalog_controller_spec.rb
- spec/fixtures/manifests/full_text_manifest.json
- spec/fixtures/metadata/e41da87f-84af-4f50-ab69-781576cf82db.json
- spec/models/iiif_resource_spec.rb
- spec/services/figgy_graphql_spec.rb
- spec/support/stub_manifests.rb
> Full Text Search

- app/assets/stylesheets/application.scss
- spec/helpers/application_helper_spec.rb
> Fixes the z-index for the "Curated features" dropdown links within the masthead

- app/services/iiif_manifest.rb
- spec/models/iiif_resource_spec.rb
> Don't wipe override title on reindex.

- app/assets/stylesheets/application.scss
> Add transparent nav-bar.

- app/assets/stylesheets/application.scss
> Fix color of dropdown text.

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/more_link.js
- app/assets/stylesheets/application.scss
- app/views/catalog/show.html.erb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/features/catalog_show_spec.rb
- spec/support/capybara_selenium.rb
- spec/support/devise_helpers.rb
- spec/support/features/session_helpers.rb
- spec/support/request_spec_helper.rb
> Adds more.../ less... link where the content of a field is too long

- lib/tasks/dev.rake
Adds the Rake tasks `pomegranate:reindex` (for reindexing a Solr Document using a IIIF Manifest URL) and `pomegranate:sidecar_clean_references` (for removing deprecated Catalog/Orangelight `electronic_access_1display` values).  Refs #446
> Adds the Rake tasks pomegranate:reindex and pomegranate:sidecar_clean_references

- app/presenters/rtl_show_presenter.rb
- spec/factories/exhibits.rb
- spec/features/catalog_spec.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Collections in show view links to collections.

- spec/features/catalog_show_spec.rb
This was triggering errors within CircleCI tests: https://circleci.com/gh/pulibrary/pomegranate/1410?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
> Adjusts the catalog show view feature test (exhibit factory slugs need to be explicitly given)

- .rubocop.yml
- app/models/iiif_resource.rb
- spec/models/iiif_resource_spec.rb
> Changing handling for errors encountered during the reindexing process for IIIFResources

- .rubocop.yml
- app/models/solr_document.rb
- app/views/spotlight/catalog/_edit_default.html.erb
- config/initializers/monkeypatches/contextual_edit_patch.rb
- spec/features/edit_spec.rb
There were a variety of problems with editing metadata of resources, and
this should clear them up.
Closes #525
> Fix editing of metadata.

- app/presenters/rtl_show_presenter.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Fixing links to collections

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/footer.scss
> fix footer content centering, stickiness

- app/assets/stylesheets/application.scss
- app/presenters/rtl_show_presenter.rb
- spec/presenters/rtl_show_presenter_spec.rb
* Removing markup from breadcrumb titles
* Fixing size/alignment of search button
Fixes #544
> Fixing display problems

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/browse_category.scss
> update box-shadow browse category

- app/assets/stylesheets/application.scss
Adds space between the category pills and the first row of collection cards.
> Adding space after category pills

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/browse_q.scss
> Fixing display of search-within browse category search box

- .solr_wrapper
- Procfile
- README.md
> Saving Solr state between restarts and running Solr with foreman

- app/assets/javascripts/application.js
- app/assets/javascripts/back_to_top.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/footer.scss
- app/views/shared/_footer.html.erb
> Fix back-to-top button - position:fixed is ignored in Firefox and Chrome

- app/views/layouts/application.html.erb
- app/views/layouts/blacklight.html.erb
> fixes footer in search results

- config/initializers/lograge.rb
- config/routes.rb
- spec/routing/exhibits_routing_spec.rb
> Fix logging of Uploaded Requests & Fix Site Masthead Editing

- app/presenters/rtl_show_presenter.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Blank override title shouldn't override

- app/controllers/application_controller.rb
- spec/controllers/catalog_controller_spec.rb
- spec/requests/catalog_spec.rb
> Handles cases where clients request JSON views of exhibit items which cannot be found

- Gemfile
- Gemfile.lock
- app/presenters/rtl_index_presenter.rb
- spec/presenters/rtl_index_presenter_spec.rb
- spec/rails_helper.rb
> Fix index display when blank override title.

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
> Fix document instance variable being required for thumbnail display

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> Search across should only have List as an option.

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> Remvoe embed from all search options.

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/views/_user_util_links.html.erb
- app/views/catalog/_bookmark_control.html.erb
- config/routes.rb
- spec/features/bookmarks_spec.rb
> Turn bookmarks back on

- spec/factories/sidecars.rb
- spec/factories/solr_documents.rb
- spec/features/bookmarks_spec.rb
and use them in bookmarks feature spec
> Add new document and sidecar factories

- .rubocop.yml
- app/controllers/pomegranate/metadata_configurations_controller.rb
- app/presenters/rtl_show_presenter.rb
- app/views/spotlight/metadata_configurations/_metadata_field.html.erb
- app/views/spotlight/metadata_configurations/edit.html.erb
- spec/presenters/rtl_show_presenter_spec.rb
- spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb
- spec/views/spotlight/metadata_configurations/edit.html.erb_spec.rb
> Add Link to Search Configuration

- config/config.yml
> Make UV URL dependent on collections configuration.

- app/services/iiif_manifest.rb
- spec/fixtures/metadata/12345678.json
- spec/models/iiif_resource_spec.rb
> Index system_created_at_dtsi/system_updated_at_dtsi.

- app/sir_trevor_blocks/recent_items_block.rb
- spec/factories/iiif_resource.rb
- spec/fixtures/metadata/1234567.json
- spec/fixtures/metadata/e41da87f-84af-4f50-ab69-781576cf82db.json
- spec/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb_spec.rb
> Sort recent items by Figgy modified date

- app/assets/stylesheets/application.scss
- app/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb
> Increase h2 font size, make Recent Additions an h2.

- app/sir_trevor_blocks/recent_items_block.rb
> Show 10 items instead of 9 in Recent Items

- app/views/layouts/blacklight.html.erb
This was breaking my dev instance
> Update search link in blacklight layout to match spotlight

- app/assets/stylesheets/overrides/dropdowns.scss
- app/controllers/catalog_controller.rb
- app/services/all_fields_label_migration.rb
- app/views/catalog/_search_form.html.erb
- lib/tasks/migrate.rake
- spec/services/all_fields_label_migration_spec.rb
refs #645; close that ticket after rake task has been run.
> Add fielded search

- app/controllers/catalog_controller.rb
- spec/features/browse_spec.rb
> Add bookmark action to browse results list

- config/config.yml
- spec/helpers/application_helper_spec.rb
> Use figgy's /viewer url instead of /uv/uv

- config/deploy/production.rb
> Restart DPUL2 workers on deploy.

- lib/tasks/index.rake
> Rake task to reindex all collections

- config/initializers/redis_config.rb
- config/initializers/sidekiq.rb
- config/redis.yml
Closes #691
Also requires https://github.com/pulibrary/princeton_ansible/pull/1219
> Redis configuration.

- app/assets/stylesheets/variables/typography.scss
Leave it for header and footer.
fixes #662
> Remove Arial Unicode MS from font-sans

- spec/services/figgy_event_processor_spec.rb
> Add a test to cover new error handling

- app/models/collection_manifest.rb
- app/models/iiif_resource.rb
- app/values/authorized_url.rb
- app/values/manifest_metadata.rb
- config/config.yml
- spec/models/iiif_resource_spec.rb
- spec/queries/external_collections_query_spec.rb
- spec/support/stub_manifests.rb
This will allow us to have the system act as an authorized user when
indexing.
> Add support for a manifest auth token.

- .rubocop.yml
- app/assets/stylesheets/components/_universal_viewer.scss
- app/controllers/exhibits_controller.rb
- app/views/catalog/_universal_viewer_default.html.erb
- app/views/spotlight/exhibits/_form.html.erb
- db/migrate/20200220193547_add_condensed_viewer_to_exhibits.rb
- db/schema.rb
- spec/controllers/exhibits_controller_spec.rb
- spec/views/catalog/_universal_viewer_default.html.erb_spec.rb
> Condensed Viewer Setting

- .circleci/config.yml
We've now migrated to Ruby 2.6
Closes #713
> Remove testing Ruby 2.4

- architecture-decisions/0006-exhibits-are-collections.md
> Add ADR for naming "Exhibits" to "Collections"

- Gemfile
- Gemfile.lock
- db/migrate/20200228182712_add_field_type_index_to_spotlight_custom_fields.rb
- db/schema.rb
The query was taking ~300ms in DataDog.
> Add field type index to CustomField.

- Gemfile.lock
- app/models/user.rb
- spec/models/user_spec.rb
> External users should be able to log in a second time.

- app/views/pages/robots.text.erb
- config/routes.rb
- public/robots.txt
- spec/routing/pages_routing_spec.rb
- spec/views/pages/robots.text.erb_spec.rb
Resolves #761
Deployed to staging, gives the desired result.
> Remove static robots file, migrating its prod settings to template

- .rubocop.yml
- app/values/manifest_metadata.rb
- spec/fixtures/metadata/12345678.json
- spec/models/iiif_resource_spec.rb
>  Add link to catalog

- app/models/iiif_resource.rb
- spec/models/iiif_resource_spec.rb
You can get some info by looking at the solr logs in the admin console. these don't log to datadog.
> We need more info about these indexing errors

- app/views/pages/internal_server_error.html.erb
> Fix a typo in the error page

- .circleci/config.yml
- .tool-versions
- yarn.lock
> Upgrade to node 12, just getting a new yarn.lock

- Gemfile
- Gemfile.lock
> Pin spotlight to release 2.9.0

- README.md
- config/deploy.rb
> Adjust deploy.rb and coveralls badge to use new default branch

- app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
fixes #836
Made edits according to
https://github.com/projectblacklight/spotlight/blob/87432cd3c8a1380f9990dacbfd10a9bc5c8530ed/app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
> Pull a Field before checking its value

- spec/helpers/application_helper_spec.rb
> Rearrange tests so as not to set expectations on nil

- app/controllers/application_controller.rb
> Silence deprecation warning

- .rubocop.yml
- app/models/exhibit_proxy.rb
- app/models/iiif_resource.rb
- spec/fixtures/manifests/2b88qc199-item-deleted.json
- spec/models/exhibit_proxy_spec.rb
> Add an "unindex" step to reindexing an exhibit

- app/controllers/exhibits_controller.rb
- spec/features/exhibits/language_create_edit_spec.rb
> Fix bug in which language couldn't be made public

- app/views/_user_util_links.html.erb
> Added locale dropdown to user util links

- app/values/manifest_metadata.rb
- spec/values/manifest_metadata_spec.rb
> Show skos:prefLabel when provided for a value

- Gemfile.lock
- app/values/manifest_metadata.rb
- spec/values/manifest_metadata_spec.rb
> Downcase keywords at save time

- .circleci/config.yml
- .rubocop.yml
- Procfile
- README.md
- config/deploy.rb
- lib/tasks/clear_cache.rake
- lib/tasks/dev.rake
- lib/tasks/index.rake
- lib/tasks/migrate.rake
so we can find them all with `$ rake -T | grep dpul`
> Namespace all our rake tasks under `dpul`

- .rubocop.yml
- lib/tasks/dev.rake
Restrict it to dev, test, or staging environments
advances #891
> Add task to delete all exhibits

- .circleci/config.yml
- .lando.yml
- .solr_wrapper
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- config/application.rb
- config/blacklight.yml
- config/database.yml
- config/lando_env.rb
- lib/tasks/dev.rake
This will align dpul with the practices elsewhere in DRDS.
Fixes #861
> Switch to using lando for dev and test

- Gemfile
- Gemfile.lock
> Remove sdoc and upgrade json

- yarn.lock
> Upgrade webpack-dev-server to address security issue

- Gemfile
- Gemfile.lock
This will get us new error reporting features like breadcrumbs.
> Update honeybadger client to latest

- .circleci/config.yml
- README.md
- spec/spec_helper.rb
> Enforce 100% test coverage 

- spec/spec_helper.rb
This allows simplecov to write a coverage report when run locally
> Move Coveralls.wear inside ENV['CI']

- spec/support/webdrivers.rb
> Set Webdrivers cache time to 0.

- app/models/iiif_resource.rb
- spec/controllers/bookmarks_controller_spec.rb
- spec/controllers/catalog_controller_spec.rb
- spec/features/bookmarks_spec.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/spec_helper.rb
> Replace document_builder with .solr_documents

- app/jobs/iiif_ingest_job.rb
- app/jobs/spotlight/reindex_job.rb
- app/models/exhibit_proxy.rb
- spec/jobs/spotlight/reindex_job_spec.rb
Closes #958 
Blocked until #961 is merged.
> Fix ReindexJob

- app/models/search_across_search_builder.rb
> Fix permission checking in SearchAcrossSearchBuilder

- app/controllers/catalog_controller.rb
> Use facet_path instead of facet_url

- spec/jobs/iiif_ingest_job_spec.rb
> Remove log entry from tests

- app/views/layouts/spotlight/base.html.erb
Adds lux and vue into base layout template.
> Fixes rendering of PUL Header 

- app/views/spotlight/metadata_configurations/_metadata_field.html.erb
closes #969
found changes upstream here: https://github.com/projectblacklight/spotlight/pull/2707/files
> Fix metadata configuration page

- app/views/spotlight/home_pages/_edit_page_link.html.erb
> Replace edit_page_link override

- spec/controllers/catalog_controller_spec.rb
closes #985
upstream reference: https://github.com/projectblacklight/blacklight/pull/2447/files
> Resolve document_list deprecation

- app/controllers/catalog_controller.rb
> Quiet ViewConfig deprecation

- app/helpers/application_helper.rb
- app/views/catalog/_default_search_form.html.erb
> Address search bar autofocus deprecation

- app/presenters/rtl_index_presenter.rb
> Address #field_values deprecation

- app/helpers/index_helper.rb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
- spec/helpers/index_helper_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb_spec.rb
> Address index_presenter deprecation

- app/views/spotlight/sir_trevor/blocks/_recent_item.html.erb
> Address thumbnail image asset pipeline issue

- spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb
> Fix incorrect tooltip test

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/presenters/rtl_show_presenter.rb
- spec/features/catalog_show_spec.rb
- spec/presenters/rtl_show_presenter_spec.rb
> Fix collection link rendering

- app/helpers/application_helper.rb
- app/models/iiif_resource.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/spec_helper.rb
Closes #1025 
- Removes unused methods
- Brings code coverage to 100%
- Sets minimum coverage at 100%
> Improve code coverage

- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
> Remove coveralls

- config/deploy.rb
Oops, these changes didn't make it into #1033
refs #1059
refs #979
> Fix cap task for replicating prod data to staging

- .circleci/config.yml
> Store coverage report

- app/assets/stylesheets/site.scss
> Widens search field box

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/back_to_top.scss
- app/assets/stylesheets/footer.scss
- app/views/shared/_footer.html.erb
- spec/views/shared/_footer.html.erb_spec.rb
> Re-add back to top button

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/recent_items.scss
- app/controllers/application_controller.rb
- app/sir_trevor_blocks/recent_items_block.rb
- app/views/spotlight/sir_trevor/blocks/_recent_item.html.erb
- spec/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb_spec.rb
Fixes broken recent items widget.
Closes #980 
Closes #1118
> Fix recent items widget

- app/assets/stylesheets/variables/variables_bootstrap.scss
> Change link color from blue to dark blue

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/_pages.scss
> Make non-active content page list elements gray

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/exhibit_cards.scss
- app/assets/stylesheets/site.scss
> Vertical align exhibit cards

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/application_variables.scss
- app/views/spotlight/exhibits/_exhibits.html.erb
These are mostly clean ups that don't really affect the way things look.
> Small changes to exhibit card overrides

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/sir_trevor_widgets/_uploaded_items_block.scss
- app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
> Stop text from wrapping around images.

- README.md
- config/deploy.rb
> Use today as the default data replication date

- app/assets/stylesheets/overrides/buttons.scss
Fixes #1162 
(Apologies, the title of this branch incorrectly references 1163)
> Reduces height of tall blue submit buttons

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/uploaded_items.scss
- app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
> Remove border from uploaded items

- app/models/external_manifest.rb
> Increase collection manifest load timeout

- app/components/blacklight/response/facet_group_component.html.erb
- app/components/blacklight/response/facet_group_component.rb
- package.json
- yarn.lock
> Replaces hamburger icon with filter icon in Limit Your Search mobile view

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/pagination.scss
- app/assets/stylesheets/site.scss
> Add space above footer and pagination element

- app/assets/stylesheets/site.scss
> Scope list style overrides to .document

- app/views/shared/_footer.html.erb
> Adds text content to back to top anchor tag to make it accessible

- .rubocop.yml
- app/services/iiif_manifest.rb
- spec/fixtures/iiif_responses.rb
- spec/services/iiif_manifest_spec.rb
> Enable embed widget for multi-volume work manifests

- app/views/catalog/_universal_viewer_default.html.erb
- spec/views/catalog/_universal_viewer_default.html.erb_spec.rb
> Add title to UniversalViewer iframe

- app/assets/javascripts/openseadragon.js
- app/assets/javascripts/pom_boot.es6
- app/views/catalog/_openseadragon_default.html.erb
> Fix item embed display.

- app/assets/javascripts/application.js
See https://github.com/sul-dlss/exhibits/pull/2139
> Add override to fix chrome render bug.

- app/services/iiif_manifest.rb
- spec/fixtures/metadata/findingaids-date.json
- spec/models/iiif_resource_spec.rb
> Index sort dates for Finding Aids material.

- config/environments/production.rb
> Configure action_mailer to use mail rely

- app/jobs/spotlight/reindex_exhibit_job.rb
- config/environments/test.rb
- spec/controllers/bookmarks_controller_spec.rb
- spec/controllers/catalog_controller_spec.rb
- spec/features/bookmarks_spec.rb
- spec/features/bulk_actions_spec.rb
- spec/jobs/spotlight/reindex_exhibit_job_spec.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/models/exhibit_proxy_spec.rb
- spec/models/iiif_resource_spec.rb
- spec/services/figgy_event_processor_spec.rb
- spec/support/with_queue_adapter.rb
- spec/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb_spec.rb
> Add support for new resources in reindexing.

- spec/features/accessibility_spec.rb
> Use inline job queue in bookmarks accessibility test

- spec/features/accessibility_spec.rb
> Add references to issues for addressing accessibility violations

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/index.scss
- app/helpers/index_helper.rb
- app/processors/list_rendering.rb
- spec/helpers/index_helper_spec.rb
- spec/presenters/rtl_index_presenter_spec.rb
> List titles in index display

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> Add fields to search result JSON endpoint for bento search.

- .github/ISSUE_TEMPLATE/kel-issue-template.md
Created an issue template to test, in an effort to give essential information in streamlined way to IT staff working on issue.
> Update issue templates 

- app/assets/stylesheets/overrides/breadcrumb.scss
- spec/features/accessibility_spec.rb
> increased contrast for navbar

- config/initializers/monkeypatches/nonexistent_exhibit_patch.rb
- spec/requests/errors_spec.rb
> 404 when requesting page nonexistent-exhibit

- .github/ISSUE_TEMPLATE/kel-issue-template.md
add"Sudden Priority" and "Maintenance/Research labels for all sudden priority items
> Update issue templates

- app/controllers/application_controller.rb
- spec/requests/errors_spec.rb
> return 404 for Riiif::ImageNotFoundError

- config/deploy/staging.rb
> Deploy staging to new machine

- app/decorators/applies_title_from_slug.rb
- app/models/solr_document.rb
- app/repositories/friendly_id_repository.rb
- spec/features/catalog_spec.rb
- spec/models/solr_document_spec.rb
- spec/repositories/friendly_id_repository_spec.rb
- Add a test that fails in the right way
- Fix FriendlyIDRepository to use current_exhibit
- Fix FriendIdRepository spec
closes #1297
> Fix title override

- config/deploy/staging.rb
> Add new staging1

- .circleci/config.yml
- .tool-versions
> Upgrade to Ruby 2.7

- Gemfile.lock
- spec/factories/pages.rb
- spec/requests/pages_spec.rb
Add a test enforcing correct permissions
closes #1313
maybe also refs #1321
> Downgrade cancan to pre 3.2.0

- app/views/catalog/_openseadragon_default.html.erb
> Don't error if no tile_source.

- spec/features/accessibility_spec.rb
closes #1337 
ticket made: #1336
> excluded failing WCAG test

- app/models/iiif_resource.rb
I think this is better. Not sure whether it will fix any of these things
but done while investigating #1294, #1291, #1340
Also #961 is interesting for context
> Use a Pipeline that doesn't load into solr when just fetching documents

- app/models/exhibit_proxy.rb
- app/models/iiif_resource.rb
- spec/jobs/spotlight/reindex_exhibit_job_spec.rb
- spec/models/exhibit_proxy_spec.rb
closes #1291
I tried to do an alias but the superclass' method is dynamically defined. this isn't particularly pretty but it seems to do the job.
> Compare bare url when checking members to remove

- docs/Home.md
- docs/Indexing-metadata-from-Figgy.md
- docs/Navigating-DPUL-Objects.md
- docs/RabbitMQ---Sneakers.md
> added wiki content to docs folder

- app/jobs/spotlight/reindex_job.rb
- spec/jobs/spotlight/reindex_job_spec.rb
and sidekiq can retry
closes #1294
> Make ReindexJob raise so honeybadger can notify

- app/jobs/spotlight/reindex_job.rb
- spec/models/iiif_resource_spec.rb
refs #1294; follow-up to #1346
> Actually raise so we can actually get honeybadger notifications

- config/config.yml
- lib/tasks/replicate.rake
- Allow development instances to use a figgy auth token
- Add a comment about turning off db connections during replication
> Updates that were helpful during testing

- app/values/manifest_metadata.rb
- spec/models/iiif_resource_spec.rb
> Use "Available online" label

- Gemfile
- Gemfile.lock
This fixes a bug I was having with current_or_guest_user erroring in
development
> Update devise guests

- .circleci/config.yml
- .lando.yml
use new cimg boxes with browser and node orbs
> Update ci config and run nightly

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/overrides/admin.scss
- app/views/spotlight/catalog/_admin_header.html.erb
> Fix InvalidAuthenticityToken on reindex

- Gemfile
- Gemfile.lock
- bin/setup_keys
- config/initializers/redis_config.rb
- config/initializers/sidekiq.rb
- config/routes.rb
> Add sidekiq pro

- .circleci/config.yml
- .lando.yml
> Prepare for postgres 10-to-13 migration

- .postcssrc.yml
- package.json
- yarn.lock
Updates packages and replaces `post-cssnext` with `postcss-preset-env`.
> Update javascript packages

- app/assets/stylesheets/site.scss
> Restore spacing between title and metadata in search results

- config/deploy.rb
> Add text file with SHA deployed

- .circleci/config.yml
- .tool-versions
> Update to Node 18

- Gemfile
- Gemfile.lock
> Add cap gems required for newer keys

- app/assets/stylesheets/site.scss
> Anchor rtl text to the right

- app/services/iiif_manifest.rb
- spec/services/iiif_manifest_spec.rb
> Use auth token when indexing a Princeton-only MVW

- Procfile
- README.md
> Remove references to foreman

- config/application.rb
closes #1442
tested on staging
> Allow IIIF::OrderedHash

- app/views/shared/_analytics.html.erb
> Update analytics tag.

- app/values/manifest_metadata.rb
- spec/fixtures/manifests/recording_manifest_6f42ab87.json
- spec/fixtures/metadata/6f42ab87-5930-4d08-a108-78fb0ab25755.json
- spec/models/iiif_resource_spec.rb
Affected dpul records will need to be reindexed.
advances #1457
> Display electronic location link label as a string

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- spec/features/accessibility_spec.rb
- spec/support/capybara_selenium.rb
- spec/support/webdrivers.rb
see https://github.com/CircleCI-Public/browser-tools-orb/issues/75
> Fix build by using newest browser-tools orb and gem upgrades

- .circleci/config.yml
> Run nightly CI a bit later. Time is interpreted as GMT.

- .circleci/config.yml
- .lando.yml
> Update to Postgres 15 for Dev/Test

- .circleci/config.yml
- .tool-versions
> Update node to 18

- app/javascript/dpul/more_link.js
- spec/features/catalog_show_spec.rb
While I was at it I made it default to "more" and made the toggle work a
little better. There's probably more we could do here, but...eh, YAGNI.
Closes #1499
> Fix more/less handling for lists. 

- Gemfile
- Gemfile.lock
- app/checks/solr_status.rb
- config/initializers/health_monitor.rb
- config/routes.rb
- spec/checks/solr_status_spec.rb
- spec/requests/health_check_spec.rb
> Add health monitor.

- README.md
- lib/tasks/replicate.rake
This would have made #1508 easier for someone less familiar with dpul
> Add indexing documentation to README

- app/checks/smtp_status.rb
- config/initializers/health_monitor.rb
- spec/requests/health_check_spec.rb
References pulibrary/lae-blacklight#381
> Add pony express monitor.

- app/values/manifest_metadata.rb
- spec/fixtures/manifests/new_recording_manifest.json
- spec/fixtures/metadata/0f28a498-3393-4d3e-907e-f3dd200fbf7f.json
- spec/models/iiif_resource_spec.rb
> Get the id from new seeAlso format

- app/javascript/dpul/pom_boot.js
> Configure Ajax to always use credentials.

- app/views/shared/_header_navbar.html.erb
- config/locales/es.yml
instead of adding ones that don't exist in spotlight
for reference: the blacklight translation file for the version we are
using:
https://github.com/projectblacklight/blacklight/blob/v7.24.0/config/locales/blacklight.es.yml#L29
> Use translations existing upstream in blacklight

- config/initializers/health_monitor.rb
> remove honeybadger health monitor notification

- app/views/shared/_analytics.html.erb
> Add Plausible.io analytics

- app/views/catalog/show.html.erb
> Adds Record Page tracking to Plausible

- Gemfile
- Gemfile.lock
- config/initializers/honeybadger_downtime_hook.rb
- spec/honeybadger_check_spec.rb
> Add Honeybadger downtime hook

- spec/fixtures/manifests/actor_groupings.json
- spec/fixtures/manifests/archival_resource.json
- spec/fixtures/manifests/chinese_medicine.json
- spec/fixtures/manifests/map.json
- spec/fixtures/manifests/mvw.json
- spec/fixtures/manifests/no_thumbnail.json
- spec/fixtures/manifests/paris_map.json
- spec/fixtures/manifests/recording_manifest.json
- spec/fixtures/manifests/search_service.json
- spec/fixtures/manifests/vol1.json
- spec/fixtures/metadata/0cc43bdb-ae21-47b2-90bc-bc21a18ee821.json
- spec/fixtures/metadata/12345678-changed.json
- spec/fixtures/metadata/82177270-5bbe-466a-85e1-e988a0f7a4f0.json
- spec/fixtures/metadata/965238bf-7850-4ae2-8830-f709c0f1b732.json
- spec/fixtures/metadata/beaec815-6a34-4519-8ce8-40a89d3b1956.json
- spec/fixtures/metadata/c7f0bb99-3721-4171-8a84-0256941e8298.json
- spec/fixtures/metadata/e9f4cdc7-173d-4bc8-befe-f786de455f11.json
- spec/fixtures/metadata/ea3a706e-dd01-478c-a428-2ef99762e392.json
- spec/fixtures/metadata/fffdaa09-b0c6-4ba3-8fe5-de6b13bd3d5f.json
- spec/fixtures/metadata/findingaids-date.json
This makes them easier to grep
> Format json fixtures as multiline

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
- spec/fixtures/manifests/publisher_1962.json
- spec/fixtures/manifests/publisher_no_date.json
- spec/fixtures/metadata/7cf437d0-c864-4230-8e76-84d117c88763.json
- spec/fixtures/metadata/8b33482f-9c15-4012-b3bc-43ae307ec2ef.json
> Configure publisher search field

- Gemfile
It was erroring on deploy something about loading rake tasks
> Put bixby back

- config/initializers/health_monitor.rb
- spec/requests/health_check_spec.rb
Borrowed from https://github.com/pulibrary/figgy/pull/6534 by @tpendragon
Closes #1577
> Root health.json errors rarely, filtered checks error if they fail.

- app/checks/smtp_status.rb
- spec/requests/health_check_spec.rb
> SMTP check should happen every 5 minutes.

- .circleci/config.yml
- .tool-versions
- Gemfile.lock
- config/initializers/translation.rb
- spec/rails_helper.rb
> Upgrade ruby to 3.2.6 and node to 22.10.0

- .github/ISSUE_TEMPLATE/devs_issue_template.md
- .github/ISSUE_TEMPLATE/kel-issue-template.md
- **Add the devs issue template**
- **Update issue templates**
> Add dev issue template

- app/services/iiif_manifest.rb
- spec/fixtures/manifests/map_v3_manifest.json
- spec/fixtures/metadata/325b4632-325f-4a93-a9c1-1ca944fcee5e.json
- spec/models/iiif_resource_spec.rb
> Add support for IIIF 3 map indexing.

- config/initializers/devise.rb
Closes #1407
Co-authored-by: Anna Headley <hackartisan@users.noreply.github.com>
> Fix user login redirect

- app/views/layouts/spotlight/base.html.erb
- app/views/shared/_analytics.html.erb
- app/views/shared/_analytics_tag_manager.html.erb
This will let AUX control how our local analytics solution works.
Work towards pulibrary/dpul-collections#709
> Add google tag manager
