Gemfile
Gemfile.lock
spec/models/iiif_resource_spec.rb

This allows for a readonly AND a non-readonly field with a given label to exist, with different metadata.
Closes #63

Allow for duplicate labels.

---

.rubocop.yml
.rubocop_todo.yml
Rakefile
app/controllers/catalog_controller.rb
app/helpers/index_helper.rb
app/presenters/rtl_index_presenter.rb
app/views/catalog/_index_header_default.html.erb
spec/helpers/index_helper_spec.rb
spec/presenters/rtl_index_presenter_spec.rb

Adds rtl for title display in search results. Closes #84.

Add rtl functionality to search results

---

app/assets/javascripts/pom_boot.es6
app/assets/stylesheets/application.scss
app/views/spotlight/metadata_configurations/_metadata_field.html.erb
spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb

Display an icon for imported fields in metadata.

---

Gemfile
Gemfile.lock
app/views/spotlight/catalog/_edit_default.html.erb
config.ru

Checking to see if the custom field was configured to view resulted a
huge number of blacklight config generations. Removing this makes 45s
load times go to 5s.

Remove slow warning message.

---

app/models/exhibit_proxy.rb

This allows exhibits to be reindexed as a whole.
It still doesn't fix the issue with the #/indexed report or deleting items that are gone, though.

Match expected interface for ExhibitProxy

---

app/assets/stylesheets/application.scss
app/views/spotlight/exhibits/_exhibit_card.html.erb

IE doesn't support the hidden backing property very well. The best I
could do was make it so that it works in Chrome and will flip instantly
in IE. Unfortunately, to do that, I had to override the classes and copy
over some of the CSS from Spotlight.

Override flipping animations for IE.

---

app/assets/stylesheets/application.scss
app/views/catalog/_universal_viewer_default.html.erb
app/views/layouts/spotlight/spotlight.html.erb
app/views/shared/_announcements.html.erb
app/views/shared/_masthead.html.erb

Remove logo. Closes #229
Move beta banner to top & align text to match the rest of the site
Change site title color. Closes #270
Add overlay hack to UV so users don't get stuck on viewer on scroll

Masthead adjustments & UV scrolling fix

---

config/initializers/sneakers.rb

Reindexing some items after getting a message was taking longer than the
60 second timeout, resulting in the connection getting cut.

Increase Sneakers sync job timeout

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/application_variables.scss
app/views/spotlight/exhibits/index.html.erb

Reduce exhibit-card image size and allow more cards per row on home page

---

app/assets/stylesheets/application.scss

Add whitespace:pre-wrap CSS property to description list element

---

app/controllers/catalog_controller.rb
spec/features/catalog_spec.rb

For reasons that I can't determine, the named route for catalog facets in our  application (`facet_catalog_url`) is the inverse of the named route referenced in Spotlight  (`catalog_facet_url`). This PR proposes an override of the `search_facet_url` CatalogController method to account for this difference and enable facet limits.
Closes #424

Enable facet limits

---

app/models/iiif_resource.rb
app/services/figgy_event_processor/delete_processor.rb
app/services/figgy_event_processor/update_processor.rb
solr/config/solrconfig.xml
spec/controllers/catalog_controller_spec.rb
spec/models/iiif_resource_spec.rb
spec/repositories/friendly_id_repository_spec.rb
spec/services/figgy_event_processor_spec.rb

This is the recommended way to handle indexing from Solr's documentation
(https://lucene.apache.org/solr/guide/6_6/near-real-time-searching.html#near-real-time-searching).
Confirmed to work in development. This'll make sync time take 5 minutes
to show up, but will mean reindexes won't result in a ton of hard
commits.

Never commit from code, only from Solr

---

.gitignore
.rubocop.yml
app/controllers/pomegranate/metadata_configurations_controller.rb
app/helpers/application_helper.rb
app/processors/custom_field_rendering.rb
app/views/spotlight/catalog/_edit_default.html.erb
app/views/spotlight/metadata_configurations/_metadata_field.html.erb
app/views/spotlight/metadata_configurations/edit.html.erb
config/initializers/blacklight_initializer.rb
config/routes.rb
spec/controllers/pomegranate/metadata_configurations_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/presenters/rtl_show_presenter_spec.rb
spec/processors/custom_field_rendering_spec.rb

Overrides the MetadataConfiguration model and controller along with extending the Blacklight rendering pipeline.  Resolves #432

Extends Sir Trevor <textarea> blocks for usage with custom metadata fields

---

app/controllers/catalog_controller.rb
app/views/pages/viewers.html.erb
app/views/shared/_masthead.html.erb
app/views/spotlight/exhibits/index.html.erb

Fixes #459 
* Restores masthead on home page
* Displays "Search Results" in the search results masthead, instead of (possibly JSON) search params

Different page title and masthead title

---

app/assets/stylesheets/application.scss

Fixes #425 
There is probably a bigger SCSS issue here, but given that we're planning to revamp the design of the front page, and probably the fonts and usage of `pul-assets` in the near term, I thought a working fix was good enough.

Making sure the correct fonts are used for li elements

---

Capfile
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/header.scss
app/views/layouts/application.html.erb
app/views/layouts/blacklight.html.erb
app/views/layouts/spotlight/spotlight.html.erb
bin/webpack
bin/webpack-dev-server
config/deploy/staging.rb
package.json
yarn.lock

Resolves #501 and also addresses the following:
- Updates webpack-dev-server to release 3.1.14 (please see https://nvd.nist.gov/vuln/detail/CVE-2018-14732)
- Updates Capistrano and SSHKit (please see https://github.com/nov/json-jwt/issues/45 for the error which was raised for me in my local dev. environment)
- Removes the npm_install tasks for staging deployments
- Fixes the overflow issue in the navbar header for collection titles
- Ensures that the JavaScript packs are loaded first on the DOM

Fixes the overflow issue in the navbar header for collection titles and disables Turbolinks

---

README.md
app/controllers/catalog_controller.rb
app/controllers/exhibits_controller.rb
app/helpers/application_helper.rb
app/views/spotlight/exhibits/_form.html.erb
config/routes.rb
db/migrate/20190214151046_add_thumbnails_enabled_to_exhibits.rb
db/schema.rb
spec/controllers/exhibits_controller_spec.rb
spec/helpers/application_helper_spec.rb

Resolves #475 by addressing the following:
- Extends the Spotlight::Exhibit Model for permitting the suppressing of thumbnails (from within the "General" configuration interface)
- Provides a thumbnail retrieval method within the CatalogController (this was necessary in order to determine whether or not the Exhibit suppresses thumbnail displays)
- Fixes the sneakers command in the README (`PlumEventHandler` no has been renamed `FiggyEventHandler`)

Extends the Spotlight::Exhibit Model for permitting the suppressing of thumbnails

---

lib/tasks/dev.rake

Ensures that IIIFResources are not created within the Rake Task pomegranate:reindex and ensuring that SolrDocumentSidecars are reindexed after they are updated in pomegranate:sidecar_clean_references

Fixes errors in pomegranate:reindex and pomegranate:sidecar_clean_references

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Overrides the ApplicationHelper#application_name method in order to use only the site branding

---

.rubocop.yml
app/presenters/rtl_show_presenter.rb
spec/features/catalog_show_spec.rb

Handles cases where the view_context cannot be used to generate collection links in the RTLShowPresenter

---

.rubocop.yml
app/services/iiif_manifest.rb
spec/fixtures/metadata/12345678-changed.json
spec/models/iiif_resource_spec.rb
spec/support/stub_manifests.rb

The sidecar is used for atomic metadata updates, but it's not being kept
in sync with removals from the solr document. This should refresh those
removals appropriately, fixing issues with strange metadata showing up
in records.

Remove stale information from sidecar.

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Handles cases in ApplicationHelper#document_thumbnail when document manifest URLs cannot be retrieved

---

.solr_wrapper
Gemfile.lock
app/models/search_builder.rb

refs #593 
Local params are not allowed anymore with an edismax query type as of solr 7.2 https://lucene.apache.org/solr/guide/7_2/solr-upgrade-notes.html#solr-7-2
This updates the query to be lucene for the join, while setting the user portion of the query back to dismax.

Fix nested query in Solr 7.7

---

app/workers/figgy_event_handler.rb
spec/workers/figgy_event_handler_spec.rb

Closes #580 
The issue was it was dead-lettering to an exchange with no bound queues, because everything's set up for an environment specific queue.

Use environment specific retry queue.

---

app/assets/stylesheets/header.scss
app/views/shared/_masthead.html.erb
spec/features/exhibit_home_page_spec.rb
spec/views/shared/_masthead.html.erb_spec.rb

Add subtitle to site masthead.

---

app/views/spotlight/metadata_configurations/edit.html.erb
spec/views/spotlight/metadata_configurations/edit.html.erb_spec.rb

This got missed in the Spotlight upgrade.

Fix missing Text Area header in metadata config.

---

app/assets/javascripts/application.js
app/assets/javascripts/sir_trevor/blocks/recent_items.js
app/assets/stylesheets/application.scss
app/sir_trevor_blocks/recent_items_block.rb
app/views/spotlight/sir_trevor/blocks/_recent_item.html.erb
app/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb
config/initializers/spotlight_config.rb
spec/factories/iiif_resource.rb
spec/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb_spec.rb

Closes #597 
This PR looks like the following:
There's an earlier commit that has a more ordered set up, but I personally liked LAE-style cards better. Here's what the earlier set up looked like:

Implement Recent Items Widget

---

app/assets/stylesheets/application.scss

I'm not sure why this additional class was added in https://github.com/pulibrary/pomegranate/pull/604/files. Removing it fixes word wrap on the show page and retains the fix on the search results page. @tpendragon do you have any recollection of why it was added?
fixes #674
Before:
After:

Generalize word-break styling

---

app/models/iiif_resource.rb
app/services/figgy_event_processor/processor.rb
app/services/figgy_event_processor/update_processor.rb
spec/models/iiif_resource_spec.rb
spec/services/figgy_event_processor_spec.rb

This deletes Solr Records when the manifest is gone and also makes it so
the IIIFResource reindexing logic handles that.
Closes #635 and Closes #684

Move reindexing logic to IIIFResource.

---

app/models/iiif_resource.rb

This is necessary for a fresh reindex.

Capture record not found if a record's never been indexed.

---

app/services/iiif_manifest.rb
app/services/iiif_service.rb
app/values/manifest_metadata.rb
spec/fixtures/manifests/recording_manifest.json
spec/fixtures/metadata/ea3a706e-dd01-478c-a428-2ef99762e392.json
spec/models/iiif_resource_spec.rb

Support indexing Recording IIIF 3 manifests.

---

Gemfile
Gemfile.lock

The new version of the gem is updated for Orangelight's Blacklight 7
upgrade.
Closes #746

Pin Pul-Assets gem to the version that works.

---

app/values/manifest_metadata.rb

It's duplicating for some reason, and we don't use it. Easier to just
get rid of it.

Delete `@type` field.

---

app/controllers/catalog_controller.rb
app/models/adjusted_grouped_response.rb
architecture-decisions/0005-resource-per-collection.md

Add ADR and comments for resource-per-collection decision

---

app/models/user.rb
spec/models/user_spec.rb

Their uid and username are both their email address. princeton.edu is no
longer appended to make the email address if the uid is already an email address.
This should be deployed to staging and tested.
Once it's deployed to prod the user account in question needs to be fixed up. One account should be deleted and the other should be repaired. user ids are 126034 and 127463.
progresses #750

Allow external users

---

spec/controllers/bookmarks_controller_spec.rb
spec/factories/iiif_resource.rb
spec/features/bookmarks_spec.rb
spec/views/spotlight/sir_trevor/blocks/_recent_items_block.html.erb_spec.rb

It looks like we were initially using the `source_metadata_identifier` as the filename for these fixtures, but at some point moved to using the uuid and now the label is misleading.

Factories stub the figgy_uuid; rename from source_metadata_identifier

---

app/models/iiif_resource.rb
spec/models/iiif_resource_spec.rb

Makes resources that failed to reindex easier to find.
fixes #710

Report noid in indexing error

---

app/services/iiif_manifest.rb
spec/models/iiif_resource_spec.rb

If a CustomField existed but had a label overwritten by the Blacklight
Configuration for the exhibit it would create a new custom field even
though it shouldn't. By comparing against the slug rather than the label it avoids that Blacklight Configuration.
Closes #731

Fix duplicating Spotlight::CustomFields

---

config/config.yml
config/initializers/sneakers.rb
spec/workers/figgy_event_handler_spec.rb

Exchanges and production queues will still be durable.
fixes #800

Make staging queues non-durable.

---

Gemfile
Gemfile.lock

Rails was upgraded to 5.2.3 as part of #601
closes #741

Make rails version more explicit in gemfile

---

lib/tasks/dev.rake
lib/tasks/index.rake

Add more functionality to reindexing tasks

---

app/services/iiif_manifest.rb
spec/models/iiif_resource_spec.rb

This should fix override title creating a bunch of duplicates.
Closes #828

Check all slugs for missing keys.

---

app/models/external_manifest.rb

Should make getting large collection manifests take a while, but
complete.

Increase external manifest timeout.

---

app/models/exhibit_proxy.rb

It was re-creating the member list (and therefore fetching the
collection manifest) once for each resource on the manifest
fixes #847

Cache member list in exhibit proxy

---

.lando.yml
config/redis.yml
package.json
yarn.lock

Fixes #941 
Also updates webpack in a separate commit. Resolves errors that occur when running webpack locally.

Configures DPUL to use Lando's Redis

---

lib/tasks/cleanup.rake

These are blocking upgrade due to a new uniqueness constraint on
sidecars for exhibit_id and document_id.

Add task to delete duplicate sidecars, resources

---

app/controllers/bookmarks_controller.rb
app/controllers/catalog_controller.rb

This removes the deprecation warning. It says it will be removed in Blacklight 7, but the new SearchService continues to use
fetch_many_document_params.
This also adjusts the BookmarksController to use Blacklight's API for it, so we won't have to change that.
Closes #937

Set fetch_many_document_params.

---

app/presenters/rtl_show_presenter.rb

Use field_config rather than string to fix BL 7 deprecation warning

---

app/controllers/catalog_controller.rb

We added these earlier in the upgrade, but we shouldn't have.

Remove authenticate and add_document_breadcrumb methods from local catalog controller

---

app/presenters/rtl_show_presenter.rb
spec/features/catalog_show_spec.rb

There should never be a resource with out an exhibit.
Closes https://github.com/pulibrary/dpul/issues/971

Remove error handling for a resource with no exhibit

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb

This override keeps several tests passing. If we need to refactor could
we do it in a self-contained commit.
closes #997

Turn on local override for render_search_bar

---

app/assets/javascripts/application.js
app/controllers/catalog_controller.rb
app/views/catalog/_bookmark_control.html.erb
spec/features/bookmarks_spec.rb
spec/features/browse_spec.rb

Enables Bootstrap/Blacklight JS
Replaces our bookmark form override with the new ViewComponent, passes the path
rather than overriding.
Closes #999
Closes #1008 
Closes #1006 
Closes #1000

Fix bookmarks.

---

app/helpers/index_helper.rb
app/views/catalog/_index_masonry_default.html.erb
spec/helpers/index_helper_spec.rb

Closes #994
- Uses `heading` method instead of deprecated `label` method in index presenter.
- Removes unused backlight gallery view override. See: https://github.com/pulibrary/dpul/issues/1017

Resolve document_show_link_field deprecation

---

config/deploy.rb
config/initializers/translation.rb

- Drop and re-create staging database before replicating the prod database.
- Run migrations after

Drop staging database before replicating prod

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/overrides/breadcrumb.scss

Redesign breadcrumb

---

app/controllers/catalog_controller.rb
app/decorators/field_stringifier.rb
spec/features/catalog_spec.rb

Fixes autocomplete without having to monkey-patch a method in Spotlight.
Closes #1157

Make title field config to_s delegate to field

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/overrides/browse_category.scss

Closes #1166 
Note these screenshots show the wash-out effect removed, but it's been replaced to give us a bit more contrast for text legibility.
full screen size:
tablet size (longer titles don't show completely):

Fix category title overflow

---

app/assets/stylesheets/overrides/masthead.scss

Fix masthead title overflow on smaller screen widths

---

app/helpers/index_helper.rb
spec/features/bookmarks_spec.rb

Closes #1165
See #1188 for a ticket that should make this workaround removable.

Resources without exhibits should not break bookmarks.

---

app/controllers/bulk_actions_controller.rb
config/routes.rb
spec/features/bulk_actions_spec.rb

- Fixes bulk tag updates by overriding BulkActionsController and removing grouping parameters
- The issue arises because we use group params to enable search across and they are incompatible with Spotlight's method use of the Solr cursorMark to paginate over groups of documents.
- I tried a variety of methods to inject this was the only one that worked completely.
Closes #1172

Fix bulk tag updates

---

app/assets/stylesheets/overrides/exhibit_cards.scss
app/assets/stylesheets/site.scss
app/assets/stylesheets/variables/colors.scss

[removed original description]
This is inspired by the stanford styling, but with the grey from our footer. It puts a 2-line max on titles to reduce awkward spaces and gives a uniform height to the title overlay to remove the bit of translucent popup from atop the bottom of the image when there's no hover. Font is smaller to make this all work with nice proportions.
see screenshot in comment below.
refs #1041

Make exhibit card titles 2-lines max, with smaller font and uniform height

---

app/controllers/pomegranate/metadata_configurations_controller.rb
app/views/spotlight/metadata_configurations/_metadata_field.html.erb
spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb

Updates "Link to search" checkbox to Blacklight 7 compatible "Link to facet".
Closes #1199

Convert link_to_search checkbox to link_to_facet

---

app/services/iiif_service.rb
spec/fixtures/manifests/recording_manifest.json

This broke when we had figgy default to `eng` instead of `@none` language. (see https://github.com/pulibrary/figgy/blob/22d1dc4f6fc00b6eba2dfd6f2346f90045f6ea99/config/initializers/monkeypatches/iiif_language_map_patch.rb#L12)
closes #1202

Fetch all presentation V3 label language values

---

app/assets/stylesheets/overrides/exhibit_cards.scss

Make exhibit card subtitle smaller

---

app/views/spotlight/exhibits/_tags.html.erb

Closes #1150 
The tags were being alphabetized but case sensitively, which is why the tags starting with lowercase letters are at the end of the tag list. I fixed this by sorting case insensitively.

Alphabetize tags case insensitively

---

app/views/spotlight/metadata_configurations/_metadata_field.html.erb
spec/features/catalog_show_spec.rb
spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb

This is what is used for lookup to find the right facet field
closes #1199 again
Note that once this is deployed any exhibits with broken facet links can be repaired by going into the exhibit dashboard > Metadata Display > click "save" on the form (this will overwrite the saved value of this field with the correct value)

Store the non-exhibit-prefixed facet name in link_to_facet

---

app/services/iiif_service.rb
config/initializers/monkeypatches/iiif_service_patch.rb
spec/services/iiif_service_spec.rb

- In a previous commit, we increased a timeout value, but this did not solve our timeout issues. 
- We need to set a timeout value on the Spotlight http_client and configure the DPUL IIIFService class to use it.
- Also important for resolving #1226, is that the[ IiifHarverster.url_is_iiif?](https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/resources/iiif_harvester.rb#L36) method uses the larger timeout as well.
- As this is not configurable currently, the only (semi) sane way to do this is to monkey patch.
Advances #1226

Add Faraday timeout value to http_client connections

---

app/assets/stylesheets/overrides/buttons.scss

Increase search buttons color contrast

---

app/jobs/concerns/job_tracking.rb
app/jobs/spotlight/reindex_exhibit_job.rb
app/jobs/spotlight/reindex_job.rb
app/models/exhibit_proxy.rb
spec/jobs/spotlight/reindex_exhibit_job_spec.rb

- Fixes repeat indexing job runs
- Allows resource monitor to return accurate job tracking data
Closes #1094

Fix exhibit re-indexing information display

---

app/controllers/application_controller.rb
spec/requests/errors_spec.rb

404 when resource is requested on a nonexistent exhibit

---

app/jobs/spotlight/reindex_exhibit_job.rb
spec/jobs/spotlight/reindex_exhibit_job_spec.rb

Refs #1267
The issue in 1267 was as follows:
ExhibitReindexJob starts, gets through the first 42 resources which are public, hits the 43rd item which is private and new, and tries to create it. It "saves", but doesn't throw an exception because it's not `save!`, and then tries to queue a job - but that new resource has no ID, because it failed validation, because it's a private URL. So the job errors, and only the first 42 get processed for indexing.

Fix reindexing exhibits with private resources.

---

config/initializers/monkeypatches/autocomplete_patch.rb
spec/features/catalog_spec.rb

Autocomplete should return titles with no HTML.

---

config/deploy.rb

We were always passing DATE before so didn't realize this was necessary.

Fix replicate command to include 'date'

---

config/initializers/sneakers.rb
spec/workers/figgy_event_handler_spec.rb

Closes #1319
Pulled new option locations from here: https://github.com/jondot/sneakers/blob/master/lib/sneakers/configuration.rb
The old values were deprecated, and it was copying the durable option to both queue/exchange here:
https://github.com/jondot/sneakers/blob/31d0cb25dc5bbcfb0749567e9e0f80e6353fb66b/lib/sneakers/configuration.rb#L107-L108

Set exchange to be durable, but queue to not be.

---

app/jobs/spotlight/update_job_trackers_job.rb
spec/jobs/spotlight/reindex_exhibit_job_spec.rb

Closes #1295 
Tested on staging. Works as expected.

Ensure that UpdateJobTrackersJob is always run synchronously

---

app/assets/stylesheets/overrides/_pages.scss

closes #1332 
Side nav is now all dark gray. Note that the active page is still bolded though.

added consistent dark gray color to side nav

---

app/assets/stylesheets/variables/typography.scss

Closes #1417
This was added in #662 and accidentally reverted in #1076 during our spotlight upgrade.
Before: 
Now:

Remove Arial Unicode MS, which breaks connecting characters.

---

Gemfile.lock
app/services/iiif_service.rb
app/values/authorized_url.rb
spec/services/iiif_service_spec.rb

Fixes indexing of Princeton-only MVWs. There was one additional spot to inject a token.
For real this time:

Add auth token to IIIFService response method

---

app/services/iiif_manifest.rb
config/initializers/monkeypatches/blacklight_configuration_patch.rb
config/initializers/spotlight_config.rb
spec/features/catalog_spec.rb
spec/fixtures/iiif_responses.rb
spec/models/iiif_resource_spec.rb
spec/services/iiif_manifest_spec.rb

advances #1287
Once this is deployed, the collection needs to be re-indexed, then the carousel widget needs to be edited to pull in the image again. after that it will show up at a larger size and not be blurry.

Index full image at larger size and make it part of autocomplete response

---

app/views/shared/_header_navbar.html.erb
config/locales/blacklight.es.yml
spec/factories/language.rb
spec/features/language_select_spec.rb

- Buttons for log in, favorites, dashboard, etc. in the user's top right dropdown still maintain the exhibit's locale. 
- These links are generated through Spotlight, and seem to use the default_url_options function in the application controller, which looks like it just runs once for the whole page so I'm unclear on how to generate links with different locales for different areas of the page.

Locale switches back to English when clicking 'Digital PUL' home button

---

Gemfile
Gemfile.lock

This is no longer an issue since later versions of bundler first install
whatever bundler version the Gemfile.lock was generated with, then run
that to bundle. This will give us a little more flexibility on server
bundler versions.
refs pulibrary/princeton_ansible#3164
reverts #1366

Back out requirement for specific bundler version

---

package.json
yarn.lock

It doesn't seem like we're using this, and vite is saying it's out of
date.

Remove caniuse node package

---

app/jobs/spotlight/reindex_exhibit_job.rb
app/models/exhibit_proxy.rb
spec/jobs/spotlight/reindex_exhibit_job_spec.rb

advances pulibrary/figgy#6329 (close once reindex is done)
supercedes #1529 -- I thought I could push the `valid?` check down the stack, but the job won't run if the resource hasn't persisted, and failed validation can keep a resource from persisting. I didn't want to rewrite the reindex jobs to take a url instead of a resource, so this PR still proposes recording the job as a failure, after some retries. It also sends more details to honeybadger.

Retry resource enqueues up to 5 times

---

.circleci/config.yml

Update browser-tools orb and install chrome without specific version

---

config/deploy.rb

The version of ActiveSupport on tower isn't compatible with this include, so get the current date this way.
Closes #1550

Fix tower deploy

---

app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb

Closes #1553
I don't have a test for this mostly because it looks hard to test, and we didn't have one before.
Before:
After:

Add direction to uploaded items block.

---

app/services/iiif_manifest.rb
config/sidekiq.yml
spec/features/indexing_spec.rb
spec/support/capybara_selenium.rb

- **Simplify capybara selenium, add run in browser option**
- **Add failing test to demonstrate bug #1587**
- **Fix the bug**
- **Index more in dev at once**
advances #1587

Index a field even when its label has been changed for the exhibit

---

app/presenters/rtl_index_presenter.rb
app/processors/list_rendering.rb
config/environments/development.rb
spec/presenters/rtl_index_presenter_spec.rb

Render titles on browse page the same as on search page

---

config/initializers/deprecation.rb

Same story as pulibrary/pulfalight#1512
This one's deployed, since if I let it run all day it'd cost money.

Silence deprecations in production logs.

---

app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb

Anna added this because of some style changes in Spotlight, but I don't
see it in Spotlight 4.6.1:
https://github.com/projectblacklight/spotlight/blob/v4.7.0/app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb#L1
This is what was causing the images to squish down.
Closes #1611

Remove item-block class from _uploaded_items_block

---

app/services/iiif_manifest.rb
spec/fixtures/manifests/3c037d85-116f-490b-8d9b-62b3fe79a563.json
spec/fixtures/metadata/3c037d85-116f-490b-8d9b-62b3fe79a563.json
spec/models/iiif_resource_spec.rb
spec/services/figgy_event_processor_spec.rb

In Figgy we recently started only sending manifests with the first title
[here](https://github.com/pulibrary/figgy/pull/6625/files#diff-8a0f639284de51b51abae05bfd1f16a1f3c13293e33d2af726d4044d6f5c43d5R47), because that's what the IIIF spec says. However, we were depending on it having multiple values for DPUL indexing.
This instead pulls the title from the JSON-LD if it's available.
Closes #1613

Index full_title_tesim from JSON-LD instead of manifest.

---

Gemfile
Gemfile.lock
package.json
yarn.lock

- **Update ruby packages suggested by dependabot**
- **Bump nanoid from 3.3.7 to 3.3.8**
- **Bump vite from 5.4.11 to 5.4.18**

dependabot umbrella
